package commit

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stritech-oss/loomlc/internal/proc"
)

// policy runs the repository's own commit policy script over message, through internal/proc like every
// other subprocess in loomlc.
func policy(t *testing.T, message string) error {
	t.Helper()
	script := filepath.Join("..", "..", "scripts", "commit-policy.sh")
	if _, err := os.Stat(script); err != nil {
		t.Skipf("policy script not found: %v", err)
	}
	runner := proc.Exec{}
	if _, err := runner.LookPath("bash"); err != nil {
		t.Skipf("bash not available: %v", err)
	}

	file := filepath.Join(t.TempDir(), "message")
	if err := os.WriteFile(file, []byte(message), 0o600); err != nil {
		t.Fatalf("write message: %v", err)
	}
	var out strings.Builder
	res, err := runner.Run(context.Background(), proc.Cmd{
		Name: "bash",
		Args: []string{script, "msg", file},
		Env: []string{
			"PATH=" + os.Getenv("PATH"),
			"GIT_AUTHOR_NAME=Ada Human",
			"GIT_AUTHOR_EMAIL=ada@example.com",
		},
		Stdout: &out,
		Stderr: &out,
	})
	switch {
	case err != nil:
		t.Fatalf("run the policy script: %v", err)
	case res.ExitCode != 0:
		return fmt.Errorf("exit status %d: %s", res.ExitCode, strings.TrimSpace(out.String()))
	}
	return nil
}

func TestSanitizeRemovesAttributionAndKeepsTheRest(t *testing.T) {
	tests := []struct {
		name    string
		line    string
		dropped bool
	}{
		{name: "co-author trailer", line: "Co-authored-by: Claude <noreply@anthropic.com>", dropped: true},
		{name: "co-author in any case", line: "co-AUTHORED-by: Someone <x@example.com>", dropped: true},
		{name: "assisted-by trailer", line: "Assisted-by: Claude", dropped: true},
		{name: "session trailer", line: "Claude-Session: abc123", dropped: true},
		{name: "session trailer with a suffix", line: "Claude-Session-Id: abc123", dropped: true},
		{name: "thread trailer", line: "Codex-Thread: https://example.invalid/t/1", dropped: true},
		{name: "generated footer", line: "🤖 Generated with Claude Code", dropped: true},
		{name: "generated footer without the emoji", line: "Generated by Codex", dropped: true},
		{name: "generated-by trailer", line: "Generated-by: Claude Code", dropped: true},
		{name: "a robot emoji line", line: "🤖 whatever follows", dropped: true},
		{name: "an agent session link", line: "See https://claude.ai/code for the session", dropped: true},
		{name: "prose about generating things", line: "The change step is generated by claude, then checked.", dropped: false},
		{name: "a sign-off", line: "Signed-off-by: Ada Human <ada@example.com>", dropped: false},
		{name: "an ordinary body line", line: "Reads the stamped version instead of the placeholder.", dropped: false},
		{name: "a line mentioning a session in prose", line: "The session id is not recorded anywhere.", dropped: false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			message := "feat(cli): print the build commit\n\n" + tt.line + "\n"
			got, dropped := Sanitize(message)

			if tt.dropped {
				if len(dropped) != 1 {
					t.Fatalf("dropped = %q, want the line taken out", dropped)
				}
				if strings.Contains(got, tt.line) {
					t.Errorf("message still contains %q", tt.line)
				}
				return
			}
			if len(dropped) != 0 {
				t.Errorf("dropped = %q, want nothing taken out", dropped)
			}
			if got != message {
				t.Errorf("message = %q, want it unchanged", got)
			}
		})
	}
}

func TestSanitizeKeepsTheSubjectAndBody(t *testing.T) {
	message := "feat(cli): print the build commit\n\nReads the stamped version.\n\nCo-authored-by: Claude <noreply@anthropic.com>\nSigned-off-by: Ada Human <ada@example.com>\n"
	got, dropped := Sanitize(message)

	want := "feat(cli): print the build commit\n\nReads the stamped version.\n\nSigned-off-by: Ada Human <ada@example.com>\n"
	if got != want {
		t.Errorf("message = %q, want %q", got, want)
	}
	if len(dropped) != 1 || !strings.Contains(dropped[0], "Co-authored-by") {
		t.Errorf("dropped = %q, want the co-author trailer", dropped)
	}
}

// The patterns here duplicate scripts/commit-policy.sh, which is the authority. This runs the script over
// sanitized messages, so a rule that gets added there and not here fails as a test rather than as a hook
// rejecting a commit the engine already made.
func TestSanitizedMessagesPassThePolicy(t *testing.T) {
	attributions := []string{
		"Co-authored-by: Claude <noreply@anthropic.com>",
		"Assisted-by: Claude <noreply@anthropic.com>",
		"Claude-Session: https://claude.ai/code/abc",
		"Codex-Thread-Id: 99",
		"🤖 Generated with Claude Code",
		"Generated-by: Claude Code",
		"Generated using Codex",
		"See https://claude.ai/code",
		"https://chatgpt.com/codex/tasks/abc",
		"https://cursor.com/agents/1",
	}
	for _, line := range attributions {
		t.Run(line, func(t *testing.T) {
			message, dropped := Sanitize("feat(cli): print the build commit\n\n" + line + "\n\nSigned-off-by: Ada Human <ada@example.com>\n")
			if len(dropped) == 0 {
				t.Fatalf("Sanitize left %q in place; the policy script rejects it", line)
			}

			if err := policy(t, message); err != nil {
				t.Errorf("the policy script rejected a sanitized message: %v\n--- message ---\n%s", err, message)
			}
		})
	}
}

// Every type the checker accepts has to be one the policy script accepts too.
func TestAcceptedTypesMatchThePolicy(t *testing.T) {
	for _, kind := range []string{"feat", "fix", "docs", "style", "refactor", "perf", "test", "build", "ci", "chore", "revert"} {
		t.Run(kind, func(t *testing.T) {
			message := kind + "(cli): print the build commit\n\nSigned-off-by: Ada Human <ada@example.com>\n"
			if got := Check([]Proposed{{Message: message, Paths: []string{"a.go"}}}, []string{"a.go"}, nil); got != nil {
				t.Errorf("the checker refused %q: %v", kind, details(got))
			}

			if err := policy(t, message); err != nil {
				t.Errorf("the policy script refused %q: %v", kind, err)
			}
		})
	}
}
